apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-k8s
  template:
    metadata:
      labels:
        app: devops-k8s
    spec:
      containers:
      - name: devops-k8s
        image: chary777/devopsproject
        ports:
        - containerPort: 8080
		
---

apiVersion: v1
kind: Service
metadata:
  name: devops-srvc
  labels:
    app: devops-k8s
spec:
  ports:
  - port: 80
    targetPort: 4000
  type: NodePort